/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorResultado;
import Controlador.ControladorTarjeta;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author AleMayhua
 */
public class VentanaTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTarjeta
     */
    public VentanaTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltarifa = new javax.swing.JLabel();
        jButtonelegir = new javax.swing.JButton();
        jLabeltarjeta = new javax.swing.JLabel();
        jTextFieldnumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarjeta");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabeltarifa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltarifa.setForeground(new java.awt.Color(51, 51, 255));
        jLabeltarifa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonelegir.setText("Elegir otra tarifa");
        jButtonelegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonelegirActionPerformed(evt);
            }
        });

        jLabeltarjeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltarjeta.setForeground(new java.awt.Color(51, 51, 255));
        jLabeltarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltarjeta.setText("Esperando tarjeta...");

        jTextFieldnumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnumeroFocusLost(evt);
            }
        });
        jTextFieldnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabeltarifa, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addComponent(jLabeltarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonelegir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltarjeta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonelegir)
                    .addComponent(jTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonelegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonelegirActionPerformed
        // TODO add your handling code here:
        ControladorTarjeta.botonElegir();
    }//GEN-LAST:event_jButtonelegirActionPerformed

    private void jTextFieldnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumeroActionPerformed

    private void jTextFieldnumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnumeroFocusLost
        // TODO add your handling code here:
        ControladorTarjeta.numSaldo();
    }//GEN-LAST:event_jTextFieldnumeroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonelegir;
    private javax.swing.JLabel jLabeltarifa;
    private javax.swing.JLabel jLabeltarjeta;
    private javax.swing.JTextField jTextFieldnumero;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabeltarifa() {
        return jLabeltarifa;
    }

    public JButton getjButtonelegir() {
        return jButtonelegir;
    }

    public JTextField getjTextFieldnumero() {
        return jTextFieldnumero;
    }
}
